name: Deploy to production (FTP)

on:
  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends emacs-nox

      - name: Build site (produccion)
        env:
          CSD_BASE_URL: ""
        run: make build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:            ${{ secrets.SFTP_HOST }}
          username:          ${{ secrets.SFTP_USER }}
          password:          ${{ secrets.SFTP_PASSWORD }}
          local-dir:         ./public/
          server-dir:        ${{ secrets.SFTP_REMOTE_PATH }}
          protocol:          ftp
          port:              21
